apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual-gatus-data
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gatus-pv-manual-data
  labels:
    type: local
    app.kubernetes.io/name: gatus
spec:
  storageClassName: manual-gatus-data
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/data/gatus
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: type
              operator: In
              values:
                - agent-b
