apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus-secrets
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: config.yaml
      remoteRef:
        key: "725089ff-9a64-4119-85f9-b3bc002a0867"
