apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: &app vaultwarden
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app

spec:
  serviceName: *app
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: *app
      app.kubernetes.io/instance: *app

  template:
    metadata:
      name: *app
      labels:
        app.kubernetes.io/name: *app
        app.kubernetes.io/instance: *app

    spec:
      nodeSelector:
        type: agent-b

      tolerations:
        - key: "manual"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"

      containers:
        - name: vaultwarden
          image: vaultwarden/server:1.35.6
          ports:
            - containerPort: 80
              name: web

          env:
            - name: IP_HEADER
              value: X-Forwarded-For

          envFrom:
            - secretRef:
                name: vaultwarden-secrets

          securityContext:
            privileged: false
            runAsUser: 2025
            runAsGroup: 2025
            runAsNonRoot: true

          volumeMounts:
            - mountPath: /data
              name: vaultwarden-data

          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi

          livenessProbe:
            httpGet:
              path: /alive
              port: 80
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6

  volumeClaimTemplates:
    - metadata:
        name: vaultwarden-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "manual-vaultwarden"
        resources:
          requests:
            storage: 10Gi
