apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metrics.yaml
  - ../../apps/zz-core
  - ../cert/core
  - ../controller/external/core
  - ../controller/internal/core
  - ../secret/core
  - ../system
