#!/usr/bin/env bash
# Build every kustomization under kubernetes/ and validate the output
# against the Kubernetes and Flux/CRD schemas.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)/kubernetes"

kustomize_flags=(--load-restrictor=LoadRestrictionsNone)
kubeconform_flags=(
  -skip=Secret
  -ignore-missing-schemas
  -schema-location default
  -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'
)

status=0

# Cluster bootstrap manifests (flux-system is generated by flux, skip it)
echo "==> Validating clusters/home"
for f in clusters/home/*.yaml; do
  kubeconform "${kubeconform_flags[@]}" "$f" || status=1
done

# Every directory with a kustomization.yaml, excluding deprecated apps, generated flux output
# and z-univ (disabled in apps/kustomization.yaml, its resources point to a removed directory)
while IFS= read -r file; do
  dir=$(dirname "$file")
  echo "==> Building $dir"
  if ! kustomize build "$dir" "${kustomize_flags[@]}" | kubeconform "${kubeconform_flags[@]}"; then
    status=1
  fi
done < <(find . -name kustomization.yaml \
  -not -path './.deprecated/*' \
  -not -path './clusters/home/flux-system/*' \
  -not -path './apps/z-univ/*' \
  | sort)

exit "$status"
