apiVersion: v1
kind: Secret
metadata:
  name: recapstone-secrets
stringData:
  DOMAIN: ENC[AES256_GCM,data:0M4eBKFBIbNQvxYlp3BfdCf2pktS,iv:CC4jv0Vn8DIuLfnJ2xxko9VWZBjgo2isiiKevxAcyVk=,tag:CYYze/d2s/ZBSd70IDY7oQ==,type:str]
  S3_BUCKET_NAME: ENC[AES256_GCM,data:j9SwAH97,iv:Iik52zEGOCal5qZA+EBhJF0EoXeLp9iEIzYt4nTDXU8=,tag:2NEA63ymL/7+WhRXDufQ2w==,type:str]
  S3_REGION: ENC[AES256_GCM,data:bpH68pTKXQhP,iv:IpKfbpElBsQaKJFgm4+hgOE2Gher4yDCpCOyDT+m9Dw=,tag:U6Zb2fz9TWfdvHcRNPwbiQ==,type:str]
  S3_ENDPOINT: ENC[AES256_GCM,data:E5Olu6BV3vQkNgh4VF02L/oDTzwlhQw0Cg==,iv:DN3xVLNhxCGD9xNHrEDj7j/cmLI9UwcmB0wNLXNBfa0=,tag:+RA85gUvY18yExvE0wsjOQ==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:RVWiSscvmiQVyEgmsZNENBHYXQPwQwxyShEX5soc4TQSBQzKFpFhRZM=,iv:GE59kOTZXFAYhR+zUsiHW+Y9+UsLec8kkr8U3sq6aB0=,tag:0QU7Ep0CpVJBMMBV/2Q1/A==,type:str]
  MONGO_URL: ENC[AES256_GCM,data:9exHC7ZRxucnvRha/QKtgpkEqAGsHh18UpngAgP4eOmKViy9rhCE7GiWt/L6QQ/gaq5QUdoFPcgRdt60TREKHK/oefNVZYN8,iv:TxKzp3anh1sSA/pLyrA1GMosFmulMSbYSdycaFIGKyI=,tag:YdxbSgC9gJF/YVNfW1/X6g==,type:str]
  GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:l5ATC+MFD+bLwpYfZJva7y9GhJ4tn6uD23ScZNtvSn4YnRS22WxxvNm+kIMsaRHzsYyn9IsO4f9tsLAg2ToiZHqbsQhF4L99,iv:BdV9OUMSpawCukc2oQwMj0AOEA0F7A8kV6hgBibCsjg=,tag:tHwWyfbfVVFOuf1rXY7VXg==,type:str]
  GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:AZDdqCADFGK3EoMvBuSjMvhGKNk6SqLphmSxi2aHb82abF8=,iv:5q8UFwYCfVf0UC+Cgxgy1PY3ymCxaiYz9a6OIsrJ4IA=,tag:WsMKg0GA3m4Fi1i5DA407A==,type:str]
  S3_API_KEY: ENC[AES256_GCM,data:LRYq39+pCotiGFM9uoaPANhkLpQ=,iv:RgKg8NVOIsLJeu6SZhoZSjBPGqI5SL9KPLqKvno+Jac=,tag:qh7CMdm2leoywFXLq23Q1Q==,type:str]
  S3_API_SECRET: ENC[AES256_GCM,data:yPaS4TQ4hWLo4q6FYGiWqi74gAi7X0YzjsaQ34o4Ta7hbrpXH1+Sug==,iv:XeZhHQ9svp8W03OV5WKFLcBE5+ZW7Q6YVj/5fblCGuY=,tag:xPwdBJi+aZ5VAjq9QOwSDw==,type:str]
sops:
  age:
    - recipient: age13mcapauq0dmyg09uz5wxtmtxzueyygrvpk0tqqfvpqft0ey5j5vshccmym
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOHBuaTR3aGlwUUcySzZx
        eUhsb2xidm1hMyt3Q0I3eW1qcEwvckR1RDNjCjBNOU5ZMU1tNm5JbklRMEh6WElm
        dWVxTzM5UXVFSThhYXQ3ZncvWXM1K1EKLS0tIEtHbFRSV0x6ZlltN29kaWV0bFRC
        U01SVHd3QitEd3F2YzN5MmJxNDRVUVEK4tliGG3Xg8fd1k69wEvKQOkmoV6HqdZp
        tt9ZN/jMN6az2Y54WAjJ/9zGyezkND4eHGKCqT7iRZ70blpRy9XNqQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T08:17:53Z"
  mac: ENC[AES256_GCM,data:lQ0WU4VLrk1VC5z4GHVx6uOqoxOmVHqzaVDkrov2LyYRry6kEDtlTCWAReyFZk/rqFRrENdMEy63vSUwJwfu/TMoX/TIUQRt6z4Tz/eKnS8J3qZVtIlbwnjEhG0GX6MZ3aaEg2U8MSI3vVUJyhh0i2QQ6i2FFwe9nBrV7KgZwuQ=,iv:xdqpoM/C6H9Z/+9u3nWyp9sD0lQjlKrGUoNWGu/MJEI=,tag:RwVLFoXBuhLXgBfSHO8CWA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
