apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: keycloak-from-caddy-ext
  namespace: &app keycloak
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: *app
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: caddy-ext
      ports:
        - port: 8080
          protocol: TCP
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: intra-namespace-keycloak
  namespace: &app keycloak
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: *app
