apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual-forgejo
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: forgejo-pv-manual
  labels:
    type: local
    app.kubernetes.io/name: forgejo
spec:
  storageClassName: manual-forgejo
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/forgejo/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: type
              operator: In
              values:
                - agent-a
