apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-secrets
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: DB_NAME
      remoteRef:
        key: "6d2d5822-b0a9-43a2-88f4-b3bc002c305b"
    - secretKey: DB_USER
      remoteRef:
        key: "6b7cb16e-1d12-4779-89e7-b3bc002c3d8a"
    - secretKey: DB_PASSWORD
      remoteRef:
        key: "dc3a59b2-0e65-45cf-9269-b3bc002c4dfb"
