apiVersion: v1
kind: Service
metadata:
  name: &app forgejo
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
  ports:
    - name: http
      port: 3000
      targetPort: 3000
