apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secrets
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: DB_NAME
      remoteRef:
        key: "a07c8b85-3d17-4656-9af6-b3bc00294ecf"
    - secretKey: DB_USER
      remoteRef:
        key: "d478424d-9c79-437a-947e-b3bc002963a1"
    - secretKey: DB_PASSWORD
      remoteRef:
        key: "4db5b86a-a256-44dc-aca0-b3bc00297f0d"
    - secretKey: HOSTNAME
      remoteRef:
        key: "03689723-4f5f-4caa-8af8-b3bd00283dd6"
