apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual-my-catatan-kuliah-db
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-catatan-kuliah-db-pv-manual
  labels:
    type: local
    app.kubernetes.io/name: my-catatan-kuliah-db
spec:
  storageClassName: manual-my-catatan-kuliah-db
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/my-catatan-kuliah/db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: type
              operator: In
              values:
                - agent-a
