apiVersion: v1
kind: Secret
metadata:
    name: my-catatan-kuliah-secrets
type: Opaque
stringData:
    DOMAIN: ENC[AES256_GCM,data:IuzuY8KjVAEfuUlE203kW506so3v,iv:U7NG7x55o35/bSLrW47e5jX6VKROJPMI084Wnebqx+8=,tag:fm/IY5oI6g0bs8Kaur5tvA==,type:str]
    SECRET: ENC[AES256_GCM,data:mdobiqIIjTOVWvVg4ttovnsRsqH+oU2Cz8Zm1JyFy1c=,iv:0P+OvoGXQxrBzOfAI+zE8vq7ExCoa8nXcqgCgRLzSbs=,tag:XzD2rz40Nbp0YyA+dRbN+w==,type:str]
    DB_NAME: ENC[AES256_GCM,data:uCxpJV89WTe6wUF/dS6+,iv:pxIqyGlocWiKwVwyoqxr7E+wuu0lVf8yMNkFQxo/ptg=,tag:7DPZX82XCtzWwE4Yh9FESw==,type:str]
    DB_USER: ENC[AES256_GCM,data:2TWYDrkFcLII,iv:5C3Nq8+C3FU6lpD1gsrmO5lus+MHGieyM40YwY7Wk9o=,tag:RlCptpoexBA665tbx3NYwQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:MA1drG6+jZmRD5W6CQ==,iv:6NrzjcpP9LVUGOs4S2AenIhLA79prsow+31EgtpJo4s=,tag:5vOOcr5UqC9JkJKhWCUcqQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:6mHuEdAkyDs7Lzs6iumOlD4zYyfg3iLztsVX8DYKcXm0cQzmdMRIyHAJsN2T3nduFyHM9nkZ9PgjkyVKvbqw+OlbaMSiH2O3D9XdU9TJbVSeNg==,iv:XBVVGvhlMYgML5bp7JNwW3xATTmBI0nka+uXcaWR+ic=,tag:nnYXETP6F7xPOnSjHNqJNg==,type:str]
    NATS_URL: ENC[AES256_GCM,data:S/img/tB+euAI0wPBlvk0gI3pe/0QB/LUfFUBYfdAVrbOg==,iv:hF2SziWCg5USdsOdHaBeVBZ6LxlS+VTUymj2w8HTaHM=,tag:ze2kjD0vhlR4rgm6fVNsTg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:pMQvX4IF1MyqHtyKZVrVu2w6sYUTU+eTZHBX4Cj2qEq5o1Nw,iv:wSVlsLuJMGz5IWGGZi/ZaHocCcVsd0Fm7FrxUXrbT30=,tag:1ITPqfKbqEo7OfZfg1QCJQ==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:YiRQcTcrjqDlIlXkMw2wSwGuqxllgHSaog==,iv:FIZTMSgXpG7YZhkHaMeOh/FTy2iPbmwvvDfilT46O3U=,tag:DIURnhEGP9vCHiz/khxK4A==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:WuCEf74tNqgX7wTmaDu9OAfJGFE=,iv:SVisqPCHKvLCgIDKDbKTQEyCDB7XodG561BOXFFh7LI=,tag:/L3wV4bhkvcHXwteG4BV9A==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:s+l0wTitF+EfeKlFu7ccX9h7lhhklLnRtbbWyDc84HF/7yd9F1u9eQ==,iv:8dRedIDHhXDo1uHQhfyKY9P2Rm65AomcBLGauLw7az0=,tag:HuSAn/98G3RiilXtQqnrQg==,type:str]
    S3_REGION: ENC[AES256_GCM,data:c6pdJUBsI+Qc,iv:2p/m3O5rc/Co2xnSBIkWwLA/K1wGqGUh2jOASE//Vro=,tag:2pl2hAXBpvx3eAefv4U3zg==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:moF76yTcRVujIwzMiLTqJigK7Z1EaY6I,iv:+170cCuwBkD0uimYfNlnU9q7rutxGhxDzXAuqkeJ8WE=,tag:fqhA2eZ7N+8qW2aVX6BhPA==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:OTmHBWIykUAMHjn2FsyfpW+/oTOTy1dwrvGwIxdJZrzOiFOzEWiRMBnWLwIQblW1kafl0aM0Pe/DJp+VOgt7cwYX/eSwIo0q,iv:wnY1mzAqz1wmeVt+w4TR7Uu3svLmqqTGlFIhFLLrVy4=,tag:2/us7uamoaxneS/bDhdQZQ==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:5F6LdmPKfxpRWpL/JXjwFGhaqPgI5iBQKD/rJPnjSh+GyaU=,iv:wtxMHLripdCCZNGyrWpM0S3GAWOC6wbOs0oNDLBzPpw=,tag:XF1jv7t13mQIujbePsnRQQ==,type:str]
    HOCUSPOCUS_PORT: ENC[AES256_GCM,data:+s8cfg==,iv:LAD6L6nDd0tn/VjTjHznwoDEQEphbL++Xlsuo4e2j3M=,tag:Vwdz2hrS7C2/Cge3jKmDow==,type:str]
    HOCUSPOCUS_URL: ENC[AES256_GCM,data:+5eZC0qIr4xpFNwEpm2Rq0ZCd7DZ,iv:DDk6ZMjrWcwQ3NWyR1FV7F58Cgein6KzW88/I03PCmA=,tag:MULadDG6oav+T3XWAU7M8Q==,type:str]
    AI_SERVICE_URL: ENC[AES256_GCM,data:YGrahXk3gW5icKmOiy2v4b9zHWCd,iv:SnGXZVEc51q2D2OmhzLh85G+T2qczXwZLU6n2f8LUjk=,tag:+HQLG8Vl/ooldGqsScfzbA==,type:str]
    EMBEDDING_MODEL: ENC[AES256_GCM,data:t0MTTOHun+3JQ1lWBiS8wy/NQQq8fRQd3QOA9PNG+rqKJI/I3PI=,iv:uXS9J0UpKHmjPvrFfuuH/GMO1VZYyj61O72bApi4ZAA=,tag:uh5ZL4ql+JlFzYviH0ebnA==,type:str]
    LLM_BASE_URL: ENC[AES256_GCM,data:PKCFe3Gpo4CWaUDh/vvDcFf2QyvhxZJCPltI2PkE,iv:8CGxs02jv7zralfd8v1/x7DRPYopUdil1RGh6H/9PAs=,tag:/79FKrw7tXU4hO/A6+vAiA==,type:str]
    LLM_API_KEY: ENC[AES256_GCM,data:92ueJdlXivSsGDPObCTzUfoIh3ULeEUnO9k0p9q0EURaN6pCWGTAZ67JhNPR2pdZjNsH5zY+Cbw=,iv:TYdh6a779t9hTmnq3PFEwuX7/Oc2JpPPtoHbFI3AI5w=,tag:1nxiIcjvOadst8we+75kRQ==,type:str]
    LLM_MODEL: ENC[AES256_GCM,data:cx7jlF5DQ/ADtYF1x9NsP5BmbA==,iv:Q+rX/I8mq7kwJUvP26itkeK0X/ddjhQIqXrmTRyz1CM=,tag:ZFWA90ssr3z03z5w7Cq7eA==,type:str]
    CHUNK_SIZE: ENC[AES256_GCM,data:os9X,iv:XDoEe0JA4sOe80+7m5/mK7+jjZ8Anllqm+WFUzjVlwA=,tag:Fc+A4GXg1TaBNHLC2gsw2Q==,type:str]
sops:
    age:
        - recipient: age13mcapauq0dmyg09uz5wxtmtxzueyygrvpk0tqqfvpqft0ey5j5vshccmym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdzNUblNSelZOZXVVSStw
            ZHVGRzZZZERNODlqaUFPTHIxRlVIL0tHU2w4ClByaUFLcEtzQ1E3b2FCdjhvcEU1
            NkJmUUVkSVZKa3ljVndhVHZTZ3lWVFEKLS0tIDhWejJNODBnVldMWEloZTE4NlJn
            Kzk3OUxuWVJ5bkFOR0lSdmFPRCtnRW8KKqr8eQwWoPRml9N/AkvPK3tHDpOnBelP
            Dwj2exSVwqGy7MrRoGreDz8iRrSrdMYU4E70D3dSJotE2N+DGHvGHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-26T03:40:16Z"
    mac: ENC[AES256_GCM,data:sBbkZuMDHA8D0Qde5R4Tk+yVMPX/rCuJg1g25BgxNSeTx5AEYWq/WyM9RmCE92PBm/qxxBpNE9WOEpSsQzufnXIK9C9ny0IbLhDqlp9UxPJS+LbNGRv8oDOa76cN8Orkeji0R1HNIO2a9pwxLu0NctbkmNoakTQFQwQ8v+aerBI=,iv:2vd2gep+tf0izCSatHj52sgiGbbiVAue5f8U+fNSKSA=,tag:VjzvweBnIFBa9CAnDOtCkQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
