apiVersion: v1
kind: Secret
metadata:
    name: my-catatan-kuliah-secrets
type: Opaque
stringData:
    DOMAIN: ENC[AES256_GCM,data:XEBETd6v2rYvXsRnua9l/WXXxexG,iv:4+qn/AbMhl8ZDBCXy3jb39+cFmLDPWtQkICmfKuLpJE=,tag:avDUyQd+QfQYBUYkvgr0nQ==,type:str]
    SECRET: ENC[AES256_GCM,data:MbHPavwGfqObLaJ4TVmuHXvIU3PqhIqcNE30+cBce0c=,iv:arMHW3GQXGOIoxRDEgskOqCIKHTRN7q0CXdzTw5QuYs=,tag:YQzuJd4qEudludSullp3qQ==,type:str]
    DB_NAME: ENC[AES256_GCM,data:aRKm1va1J2EMRLrJmBeK,iv:UFKIwkDr5Q1mHtQcwjz7mllWzUpxLRwhRp7P/eV/0jY=,tag:Bv1SdDPywrVqWYN3nwPsng==,type:str]
    DB_USER: ENC[AES256_GCM,data:56Z4IwmaPzeL,iv:0o8Ry68jmR5BCvqVzpoc8JslU4CaooJL0Iekp7QV7ZI=,tag:8tl0I1vUmr2wP5eCjmxe0g==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:qAXSvvP1XXG47uforA==,iv:L2HgRDQBX7N+oRVF4WUUQ3V3C4qtSEqh6sVj7Ou04vw=,tag:jHc3WTukKBsfvVB9Iusiiw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:seIbUlwxLttA5oYHLovLYnXCBuvibNkLDx+FdOjT20/UGpvqCu9Se3PExwIYUTqgNtqVfQsf9UAPQqMK4vTIrTGYsyqKsMlBGl00Qb6/OmxHvg==,iv:jdxu/ZYYbG3WUYEumhxNuCE9J9lZR3l2foMcIJ1ciTU=,tag:PDRzWYziOYY65J13bFUaHg==,type:str]
    NATS_URL: ENC[AES256_GCM,data:qfTD9weVRsTgeEFi54VsfDnuAPo3fQPQd7dqk2ebVBXUVw==,iv:vpuTQp63oSuvZRuoqWii1AbLXDJVr5+1QhBfSMahd8g=,tag:nRNH+fjvsVIcMjoyUa1aig==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:ziTCeQSCTsg4Yz9aCyTOqX5xhTmPRw1zLv5jrAFw1IHqRXUB,iv:IOqNe39criqRUUavc48b2PPrEvV4UdhfBVGOXYC/UiE=,tag:qht1lPlBAWMukkIrDPo6uQ==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:B+WR7Jc6HqYxG2uUy/dY7R7dLCNyXds9VA==,iv:j0STZj7vB+AahzLEkR7LcYQvXkX8Xsbb162s5VgT1vI=,tag:HypSsyH5xKkMF6wmE5yNhA==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:5vGEEBA0UyOwSL8CjW2rFgDZu4A=,iv:Dpdxo7CUv7Yom6wGmlUZLPrN/7SYDIRTFlJYm4ONFeU=,tag:7yYNUE0fW+RV3mpTA0qURg==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:67z8FR7KOt19y6Q9PGb6pwbeBIUNcBoMhqO2QFZ9E9fpOKhDj4szmg==,iv:6yrbhT+bFsbi52+L05MMsU/BLPLz2+eASDodPSiasOc=,tag:9aU0NKpNYUi7pyGk0M8eWA==,type:str]
    S3_REGION: ENC[AES256_GCM,data:MyU0GBTBNK1d,iv:jW/nBjtPvibKuBlGe5o8iVqBAzLoKfP1dYaqrUN7IC4=,tag:b/vbGk6yM8n87IUOG1axjQ==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:MY7nXrcG/bItIha6uvD7ZUPgvsZPPOXh,iv:QPWvHYjYVhTm/u29ZcWMZt+9ZjAekGp/h16WkxM7oeM=,tag:KeiR7pwsjyGEUzSwJMWigg==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:i5mdf1UCFBlylgP5esfOE8CPRbiBftohKDXudDKBmplsG9OQjQKWPWIFHkpTzx7jn6vTN/Luav2LtgPeRVbiOx03N6HLMZu7,iv:PcABDNsZww41HhHE21NqXYJuj9fJHzkCkgV4MjCnyRc=,tag:g/2CgJqUHq9TebnG+WJjFQ==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:8IpvielD3hzvZwGL4nv70EE9Qml070UHH1wcWdxY6vLHKA==,iv:qrI8TtdcqclD3LhslBLVnKrpgwQhWeRodJfbxJzG3Fk=,tag:coqfc/jW9BGa11ViKr89jA==,type:str]
    HOCUSPOCUS_PORT: ENC[AES256_GCM,data:L9ktHg==,iv:jysrTKYQU4m5CZLguBYcYTrctPb+gsFAWT3hy+2huF0=,tag:JHD/7ePMSVoBijaf7GD8kg==,type:str]
    HOCUSPOCUS_URL: ENC[AES256_GCM,data:wWi1TXSpk941opN1cw2bjJ5vNCeJXg==,iv:x/IiAWRPt3t/0N6KfVbUlWV2JYiFXMZu/kcNiCcHG0U=,tag:sSJwZza2XpZq+uH5vr2rKQ==,type:str]
    AI_SERVICE_URL: ENC[AES256_GCM,data:A76M3StywznvBKDEr5k=,iv:HifiyKLvwLUoxv2EBbmOtGT8mBzxlOvXe4YMlwhTBYw=,tag:w7lFUhLQeDDPVdCjnfuqGg==,type:str]
    EMBEDDING_MODEL: ENC[AES256_GCM,data:wUnKHJf2t+bncCAndQ9zqV454lxN+NfSd/uXSDXVMMhzbst2t3s=,iv:xhdA08Bpwv3MEnZuZuUw9kbG91Vk5aMTQSb7+89aa3o=,tag:TChycQyRs66IaHU583EWUg==,type:str]
    LLM_BASE_URL: ENC[AES256_GCM,data:EL+gr06YEJgd9Q+XqvtZZD56yX0k0aPnXaYLPKPddT/Ui3E=,iv:Z3A6wTLpJ2YYj3rJ53UoDnOwZI706Rc/ngnS6x9Gays=,tag:xkjR+IxaxpOFk2+wKY3W4g==,type:str]
    LLM_API_KEY: ENC[AES256_GCM,data:hjby25E/4Fh/qnBgfF6LQ+iEjJRIlLrNB+uTHOPYDdkM5rexzzgRvH+reSXz/BR56pWW+WMm1B3A1gNNiMhB/AMQIuUDbQ==,iv:AAi/jOx/ELN5b0iMeald4LWCtM6jAuPPIfUOCo0PFOM=,tag:mLolw5KnqNIDSFASoTvJqw==,type:str]
    LLM_MODEL: ENC[AES256_GCM,data:DoOdtBJ9VeG5tuBNknX7pl5KQoWbLw==,iv:86qyslrgT7Q+46m8gg0Kwxy+Qvz1uCWA67r2NU7wiNU=,tag:kTe9fDZ9+3lug1gAIvWPdA==,type:str]
    CHUNK_SIZE: ENC[AES256_GCM,data:DnGn,iv:zkQURRZPMWZMq72y8kHxxUaTBAQRt4PFQVI2b+8kF8k=,tag:Td73T/Fp4yAk9l+NGDDRpA==,type:str]
sops:
    age:
        - recipient: age13mcapauq0dmyg09uz5wxtmtxzueyygrvpk0tqqfvpqft0ey5j5vshccmym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYTRJd2NSZ3dhVkxyQUFr
            dUlVNkRITkkvNGo3YTZRZE5EVEF5ZTBNOG00ClkrSkRIS0pFbnhibXVUMVFkalpq
            Ull5U05ubEFFZEdVTFVhelJ6VDhjeTgKLS0tIEpRdlliYzk0NldCSTFtTmFka0Iw
            ZmRjcXM5cFpsMTQ2UmlBVXlFbEJHcjgKrjStEKI+bILeFQ5b/6Hlr0r2XSvwNNPF
            wTIaykAUZ6yYEPlwfT49Va/blfx3bpkgJQgs2PP0r3H7l8BYThk4/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T02:44:57Z"
    mac: ENC[AES256_GCM,data:b986V7QvyQHDtKK/v90gsejnYZ+G2T/LucNQazRpY5a2aRDdZH1Lcd8a0QhJulUQHtu1Ti8JAsHHaoAehkUYnFtWjk8Yjm0dJu8nauUjCFnRqOiYcfcPiTE1QdX7CSfkJhIvemhItTAaAhHDnzP1dTazQ0HRIb5EqFj609vgAYE=,iv:iLRoQP/4dHa7Zh3PAc+LoQcyq3Hif4MFG1SGDD1GfyA=,tag:OlD1wqfpgJecnmkWdX+BcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
