apiVersion: v1
kind: Secret
metadata:
    name: my-catatan-kuliah-secrets
type: Opaque
stringData:
    DOMAIN: ENC[AES256_GCM,data:KZ6VorYek4iv1JpbsMRvqA6LLKBl,iv:jqEH/c4G46nsWFcsQqUNn6yU404LBUGiPdSr4aKAz6I=,tag:p7gV8K20U3rXZBVoX9yxhw==,type:str]
    SECRET: ENC[AES256_GCM,data:J5GihqFJVjTfvwoHdZY456gCvijei1zT28ySvGC/WYA=,iv:fSep2bldlxzYE2X8jwbWwq6uigqLL0xYDa5D6uqzRfA=,tag:Y/YRaHXh+8gSnRaSoCMUjQ==,type:str]
    DB_NAME: ENC[AES256_GCM,data:M1pM2orpp0efF/TxvyX4,iv:ZcO5I1VRHyd/HAxhk4mXOJxE6XNHKjVe8Zul0ILGTQc=,tag:YMoHiQxJaYjn/idKxgwUog==,type:str]
    DB_USER: ENC[AES256_GCM,data:r8qM+6tvX520,iv:1RC2Eui6soq31BUDooSEO+WmTnmZyfMT9w/XGHirYq0=,tag:ONR0BLHlirsTdn06cKf0yg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:SKuTpsPfe9Mb21U4VA==,iv:EYoSTH/I13LsdBhgrWDrl30u//P94ybE11sHV+jX9R0=,tag:v3AdlMIn74hASoloC+voAg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:JfVpTGVet6HQTojKQ1rR2KKzBWlCCalZYVZYZs+miumZ5diUnVbR82wSljkCfGaUT3nDc50svawtQ8LjmEq7jEOheOVHgEuqOjfF13ocf2l30w==,iv:YRGRvKbueAoJzdPNgqaQLARGEV/H0F99V61+dF8zcSo=,tag:Uwfvvg5/W3dTbHkNAqpldw==,type:str]
    NATS_URL: ENC[AES256_GCM,data:Panz9R6s9IB2OQ0eViYDg2o8MiHfxpXz+oIu2DeHJQqElQ==,iv:wIR8WoIAElJFLGBTIToH9oO2Vy0qs5tN8nfozzinUa8=,tag:50FFuy2GtsxyH5oWw+ivsQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:w20ub52hRPxtXT5G7IEnJ93SBkuPqwKAXpHW5WsS5m0I78kc,iv:Ce0kXgkAOhAv/ham8MLhNKtm59reOKiKdhjUkNzhseM=,tag:3FltDJmoOqxPSeK+CWFkZw==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:yS8qJomSfymRIBnAQrKJqcPcPqPoy3+uBg==,iv:DwAQv2iAsxYK9xEge/FXJicLI1JM++vcd0BBDAukxCE=,tag:IlpUfbd+v2AbHWSLcgtz+w==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:OkuT+ltD0VkjHcGkzwOK2yux+UA=,iv:cH8yKcpKGQw3fULQdMeXkr5Vh/2uBLwqLFz8F0FyTBA=,tag:Al12C7Io6F8aaXq+tMTmuQ==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:39MgJlaZPdC47SwXMyHgrh6gFSlm6EIiI5zXJ4YYITg2cpGw5vMCGw==,iv:oWhXsRAwnVSw2Xn2sxlJyFumv/Up247ACUAgTl0INrs=,tag:VcJa+upN75aLDyBUOi37Vw==,type:str]
    S3_REGION: ENC[AES256_GCM,data:OMdW9cnub7Me,iv:cIy8ZholBisvtQBBpdxwEuMn0bkoNvjaHnF2H59Q40k=,tag:NaWAi3Ed8ltVaaY6E06eTA==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:BiEpDRL24TQxqAZDMlgPynZsEFkY3B6J,iv:TzMBk8WsGWhQWxM42ovQhG2G77C/P+WTCckfIb2LgAU=,tag:RcApzVItIxprYzIW3faX2Q==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:I0d+DKSnnZLiK8NGEDPdUvBwf5zyYsFGETNbBVLnSpsMBmPoocVs7HGl7Og003Ct3rqjgzUiNcSADVif4MHQVQFHNPd3sU/5,iv:UO4qxiSCsWMwEdZMh+iEPRUzZsW4uucDR4Xt9J9Nvv0=,tag:q4fF7nD6vE0D9cDO8tdwWQ==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:iVHIrd3eR/Ddp7jlmSHIA7ctuwHmsaqrIUHNRFyyF4ov8R4=,iv:clhlbcu20W6xAo2D3TJI0BWBviW6/483N5ztMDoKYm0=,tag:zGYGtwMmfBHkElOLlZNCuA==,type:str]
    HOCUSPOCUS_PORT: ENC[AES256_GCM,data:VkbqwA==,iv:/ctKyXsVSitwRrqhw0K5XZst2nMDY8PWTXKw4eBo9n0=,tag:aY/9tf2jGRpz1c5Hzt0BwQ==,type:str]
    HOCUSPOCUS_URL: ENC[AES256_GCM,data:tBSUtynwe07/1pvkB5g2zzPuopTR,iv:ey113och2rEK1kWkczRtWuXnSwEfp9tJAGv69kB7QAA=,tag:CfPgVL0msDijV2s7o9N/SA==,type:str]
    AI_SERVICE_URL: ENC[AES256_GCM,data:i7eO7CZydDT/fbly+WiD/ycOL6Et,iv:r/muKdLdL/rzFjedvPhhJ7cP/gFJ+k0zfOjuGKnnT8k=,tag:hCoJm3PL/WUYf8gR6qSZRg==,type:str]
    EMBEDDING_MODEL: ENC[AES256_GCM,data:R9A80Gys7A8xNqHci+rixljsK8J1dQCczMiBrEUEDXxiR8NNM04=,iv:FF9J0uU6RzWor/azzbJrM80ale6yc0PjNb4nMJhiQ2Y=,tag:JnGW6QOAir8w0uVDcy5bGw==,type:str]
    LLM_BASE_URL: ENC[AES256_GCM,data:0fx0uX0AumGBzdfnMhyH9ocNSQpMiIIRUeydeGZUrepnvdV4nnzOgfGXkz7fcg==,iv:W2Krk9hvW1EYiS0hVNiEWeHWZoRJDqDDbWzv7t7WiWA=,tag:x8RM5AtbxkWj6Is+ClmkUQ==,type:str]
    LLM_API_KEY: ENC[AES256_GCM,data:QBz9YlZP51ch6187ZxryyHN86Lz68TeJdvoHdWc/iGx0H/xAM6ID1qQzUqq5ug==,iv:p0+YYfUHrXT1PRkr1vIQIqQsCVOh3UMC505t7UNz1tE=,tag:BuC43sSw/b3CCaAvfcKcng==,type:str]
    LLM_MODEL: ENC[AES256_GCM,data:18xLU0i2lC4KNjUNx7JmzMFhhFE=,iv:5ScKIIYGZOR6TFSq5S226BtKBGgjBpbR5JrRX+80WRI=,tag:pzRp3BxEBGqixc5QjmFhPw==,type:str]
    CHUNK_SIZE: ENC[AES256_GCM,data:MDVo,iv:xvQw5P3OnfbiUM+uC1A4GtJbqSW54rzmT9dvas4g5Vs=,tag:Ksr0MmMEUp4rUj1aJRk0NA==,type:str]
sops:
    age:
        - recipient: age13mcapauq0dmyg09uz5wxtmtxzueyygrvpk0tqqfvpqft0ey5j5vshccmym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Z0JuNk5QQ3RPcUNwZVdJ
            T0oxRUVFUWw0clBjSGV4S3RhZzhFSmtuNVFnCnRVQUQ4dW5VcjFxTWRFTFo1ZnNK
            cFVzbmNvOE4wTkRmWE9MUmpvWmd0QWcKLS0tIG5oeFp0a3RHYUVaRTRWak5ZZ3pV
            SmVrOUZ5R3loR1dLTnUyc0dleHJxNHMKc+tUSH3ExPcmtnj5DDecJX3JPHB5JR9J
            B9/nODLBmQadCIiPed7faLcFFxe3fQYVczdZX3opehdQDBBeV/0Kfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-26T03:25:42Z"
    mac: ENC[AES256_GCM,data:Ja2wxv4pRdKBrPmOiVbgwdtkFJxy/0hcgDDWgi1LfadkM3+UkvGQtVvuFj8zV04JnVtBbbrvxs3slB+XHAQWuDS4uHj8BBjJeGIzTZG+DP0G+fPzTulW//RcF8pSr+0Dtpi1BkFIZ8lHnAxEQ93w9FmWx5eqn6iJSE+XkafOPJY=,iv:uBycTu1TYwc8UQsBRJKL3uhabBU6KfV24UpObF7r5gU=,tag:Bk2O5vIZMSR8FIH9biYoKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
