apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-secrets
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: DB_NAME
      remoteRef:
        key: "99656921-c8b8-41a5-bd62-b3bc00228a26"
    - secretKey: DB_USER
      remoteRef:
        key: "3491a8db-b2b7-48cf-b42a-b3bc0022c438"
    - secretKey: DB_PASSWORD
      remoteRef:
        key: "409ad3ca-998d-42d1-8251-b3bc0022e6c4"
    - secretKey: DATABASE_URL
      remoteRef:
        key: "3ce352a6-c871-4e43-9aa5-b3bc00267953"
    - secretKey: URL
      remoteRef:
        key: "263d2601-eba0-43e7-8a34-b3bc00231f34"
    - secretKey: SECRET_KEY
      remoteRef:
        key: "687de086-84ad-4a4a-a319-b3bc00236345"
    - secretKey: UTILS_SECRET
      remoteRef:
        key: "925bd58e-c63b-45ed-8d49-b3bc002373f9"
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: "93b88cc3-5db5-4c56-9da8-b3bc00238745"
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: "cb8fd5c4-10d2-48fa-94c1-b3bc00239b89"
    - secretKey: AWS_S3_UPLOAD_BUCKET_URL
      remoteRef:
        key: "2145cc55-f5f1-4f76-9f83-b3bc0023b905"
    - secretKey: AWS_S3_UPLOAD_BUCKET_NAME
      remoteRef:
        key: "fe1d0606-b450-4e7b-a458-b3bc0023d173"
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: "55963b43-594c-4f73-8246-b3bd00359a80"
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: "6581fe0c-c9ae-4d6b-a9ad-b3bd0035b908"
    - secretKey: OIDC_AUTH_URI
      remoteRef:
        key: "241f65b0-8775-4342-8e88-b3bf009cd992"
    - secretKey: OIDC_TOKEN_URI
      remoteRef:
        key: "f8339a01-2c8b-4e42-acb8-b3bf009cedf2"
    - secretKey: OIDC_USERINFO_URI
      remoteRef:
        key: "0b24fb6e-244f-4f6b-9010-b3bf009d0b58"
    - secretKey: OIDC_LOGOUT_URI
      remoteRef:
        key: "64327b25-dee3-4ae6-9a81-b3bd00509e1e"
