apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-config
data:
  Corefile: |
    .:53 {
        forward . 1.1.1.1
        log
        errors
    }

    hilmo.home:53 {
        template IN A hilmo.home {
            match .*\.hilmo.home
            # Use {$ENV_VAR} syntax here
            answer "{{ .Name }} 60 IN A {$HOME_IP}"
            fallthrough
        }
        log
        errors
    }
