apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dns-secret
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: HOME_IP
      remoteRef:
        key: "5232f71f-250d-4d91-99e4-b3bc002e4a82"
    - secretKey: TS_AUTHKEY
      remoteRef:
        key: "0571e8c2-df5a-4c31-9d51-b3bc002e342e"
