apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-cloudflared-ingress
  namespace: cloudflared
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
  ingress:
    - {}
  policyTypes:
    - Ingress
