apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-backup-secrets
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: "ee362c7d-2c88-4b52-925d-b3c6009abcb7"
    - secretKey: RESTIC_REPOSITORY
      remoteRef:
        key: "7bbe7a3d-70b0-43c9-8e13-b3c6009b399d"
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: "5d173dd4-8e11-4aa9-8ae9-b3c6009aeaaa"
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: "9c13d864-b3de-419f-a9a8-b3c6009b0885"
