apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual-vaultwarden
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-pv-manual
  labels:
    type: local
    app.kubernetes.io/name: vaultwarden
spec:
  storageClassName: manual-vaultwarden
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/data/vaultwarden
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: type
              operator: In
              values:
                - agent-b
