apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-secrets
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: ADMIN_TOKEN
      remoteRef:
        key: "00a4e35d-01d9-4ebf-a913-b3bc001e37f2"
    - secretKey: DOMAIN
      remoteRef:
        key: "d55a21f9-51bf-48ae-ad4c-b3bd006f7b33"
    - secretKey: SMTP_FROM
      remoteRef:
        key: "72c512fb-70a0-47da-9afb-b3bd00a7d742"
    - secretKey: SMTP_HOST
      remoteRef:
        key: "71883408-b9b0-44db-983f-b3bd00a772ac"
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: "b6528765-b001-4c68-85cb-b3bd00a81484"
    - secretKey: SMTP_PORT
      remoteRef:
        key: "0c8ab6e8-3b7d-4a1c-a5f1-b3bd00a7828e"
    - secretKey: SMTP_SECURITY
      remoteRef:
        key: "5391c3dc-3b78-45ec-b83b-b3bd00a7c3cb"
    - secretKey: SMTP_USERNAME
      remoteRef:
        key: "475a1bcd-678d-4983-af23-b3bd00a7ef39"
