apiVersion: v1
kind: Namespace
metadata:
  name: podinfo
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: podinfo-from-caddy-int
  namespace: podinfo
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: caddy-int
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: intra-namespace-podinfo
  namespace: &app podinfo
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: *app
