apiVersion: v1
kind: Namespace
metadata:
  name: forgejo
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: forgejo-from-caddy-int
  namespace: &app forgejo
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: *app
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: caddy-int
      ports:
        - port: 3000
          protocol: TCP
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: forgejo-from-caddy-ext
  namespace: &app forgejo
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: *app
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: caddy-ext
      ports:
        - port: 3000
          protocol: TCP
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: intra-namespace-forgejo
  namespace: &app forgejo
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: *app
