apiVersion: v1
kind: Service
metadata:
  name: &app outline
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
