apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-token
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflared-token
  data:
    - secretKey: TUNNEL_TOKEN
      remoteRef:
        key: "f0a601d0-3544-4702-8ff6-b3bd00840638"
