apiVersion: v1
kind: Namespace
metadata:
  name: caddy-int
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-caddy-int-ingress
  namespace: caddy-int
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: caddy-int
  ingress:
    - {}
  policyTypes:
    - Ingress
