apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual-adguard-1-conf
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-1-pv-manual-conf
  labels:
    type: local
    app.kubernetes.io/name: adguard-1
spec:
  storageClassName: manual-adguard-1-conf
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/data/adguard-1/conf
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: type
              operator: In
              values:
                - agent-b
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual-adguard-1-work
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-1-pv-manual-work
  labels:
    type: local
    app.kubernetes.io/name: adguard-1
spec:
  storageClassName: manual-adguard-1-work
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/data/adguard-1/work
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: type
              operator: In
              values:
                - agent-b
