apiVersion: v1
kind: Namespace
metadata:
  name: outline
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: outline-from-caddy-ext
  namespace: &app outline
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: *app
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: caddy-ext
      ports:
        - port: 3000
          protocol: TCP
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: intra-namespace-outline
  namespace: &app outline
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: *app
