apiVersion: v1
kind: Namespace
metadata:
  name: caddy-ext
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-caddy-ext-ingress
  namespace: caddy-ext
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: caddy-ext
  ingress:
    - {}
  policyTypes:
    - Ingress
