apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secret-store
  namespace: external-secrets
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com.
      identityURL: https://identity.bitwarden.com.
      auth:
        secretRef:
          credentials:
            name: bitwarden-access-token
            key: token
            namespace: external-secrets
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      organizationID: ENC[AES256_GCM,data:syxcAYPp9gKfaF5sLopJNUbAhWDb3LVSwyq3gymoDYPTWK0e,iv:jPbZBcU+N1cqfZxA/9OkOF182rfNBjVBLrF0v+yGV3w=,tag:ZdHLn+4He13uUBMAu+dniA==,type:str]
      projectID: ENC[AES256_GCM,data:y1Wx1CmbrI68b2vwKZt+oMZ/SRqcG1OAflcOO7DUL8xLZGOJ,iv:UzSF6Rp9MTq/ZxcveAswkHyv5aWZkBOscLxA2rSkkEM=,tag:Mle7rWN12jzMfDifFdrrxA==,type:str]
      caProvider:
        type: Secret
        name: bitwarden-css-certs
        namespace: external-secrets
        key: ca.crt
sops:
  age:
    - recipient: age13mcapauq0dmyg09uz5wxtmtxzueyygrvpk0tqqfvpqft0ey5j5vshccmym
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdGlldEN5VlM4L1podWJ0
        QTZHY1RJRTVnSmhCNDV0S2kvbnZ3TjlwUlNVCk5hZWFSZDloMW9WVFprVUhPMTRL
        OXJkekRKbnNoLzNSZldFN3FxeUE4R1EKLS0tIGxQSGhLN1hNK0RHYis1UzFNRHcy
        Z0g3dk1GRmU2SG1iZkx1cS9nK3p5VkUKHroZtIlO4f+u01OVQzRBq0l+Ex0ZmfX8
        CCJJpWROEKbPoGcW0XB3xTU+Vn8mAgh8bH9wo1vnbbauhjU5VNwvdw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T02:44:04Z"
  mac: ENC[AES256_GCM,data:MhDri+kg68y//rZSS/ag3dKN/u4IoZMr8N8kQP2EtDIGbXwZ/VANS9tJ6FA6otQrNccDASDhZuVlXFzmWUWbAAisAgnG5lchaDnuBGByt03gtYngmj5THI79/618NwChDBM0j5uIvva1OmVSGvl3Z1KdvDXlgJ120/iQqiSXA1E=,iv:BHoB1tpW0A2OXn9tBfFrf5kACX2DzZNVwVADcMdx8aU=,tag:YjEIncoHk+rkzXys2fCSnQ==,type:str]
  encrypted_regex: ^(organizationID|projectID)$
  version: 3.11.0
