apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: &app adguard-1
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: *app
      app.kubernetes.io/instance: *app
  template:
    metadata:
      name: *app
      labels:
        app.kubernetes.io/name: *app
        app.kubernetes.io/instance: *app

    spec:
      hostNetwork: true
      nodeSelector:
        type: agent-b

      tolerations:
        - key: "manual"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"

      containers:
        - name: adguard-1-dns
          image: adguard-1/adguard-1home:v0.107.74
          volumeMounts:
            - name: config-volume
              mountPath: /opt/adguard/home/work
            - name: work-volume
              mountPath: /opt/adguard/home/conf
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
          securityContext:
            runAsUser: 2025
            runAsGroup: 2025
            runAsNonRoot: true

  volumeClaimTemplates:
    - metadata:
        name: config-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: manual-adguard-1-conf
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: work-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: manual-adguard-1-work
        resources:
          requests:
            storage: 1Gi
