apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-secrets
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: TS_AUTHKEY
      remoteRef:
        key: "cef8bc9c-757f-469d-8bec-b3bc002ee4ac"
    - secretKey: TS_EXTRA_ARGS
      remoteRef:
        key: "4f246916-b7a4-41a1-8ebf-b42200a8634d"
