apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: otel-secrets
  namespace: otel
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: GRAFANA_USERNAME
      remoteRef:
        key: "db43d785-2aa1-4502-9034-b3bc001ac0a5"
    - secretKey: GRAFANA_PASSWORD
      remoteRef:
        key: "4e344576-e58a-4aa9-ab07-b3bc001ad11a"
