apiVersion: v1
kind: Namespace
metadata:
  name: adguard
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: adguard-from-caddy-int
  namespace: &app adguard
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: *app
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: caddy-int
      ports:
        - port: 80
          protocol: TCP
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: intra-namespace-adguard
  namespace: &app adguard
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: *app
