apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual-caddy-config
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: caddy-ext-pv-manual-config
  labels:
    type: local
    app.kubernetes.io/name: caddy-ext
spec:
  storageClassName: manual-caddy-config
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/data/caddy-ext/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: type
              operator: In
              values:
                - agent-b
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual-caddy-data
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: caddy-ext-pv-manual-data
  labels:
    type: local
    app.kubernetes.io/name: caddy-ext
spec:
  storageClassName: manual-caddy-data
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/data/caddy-ext/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: type
              operator: In
              values:
                - agent-b
