# https://taskfile.dev

version: "3"

tasks:
  proxmox-i:
    cmd: uv run ansible-playbook proxmox/main.yml -i proxmox/inventory.yml --tags install

  proxmox-create:
    cmd: uv run ansible-playbook proxmox/main.yml -i proxmox/inventory.yml --tags create
