apiVersion: v1
kind: Namespace
metadata:
  name: dozzle
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: dozzle-from-caddy-int
  namespace: &app dozzle
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: *app
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: caddy-int
      ports:
        - port: 8080
          protocol: TCP
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: intra-namespace-dozzle
  namespace: &app dozzle
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: *app
