apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard
  - adguard-1
  - dozzle
  - forgejo
  - gatus
  - keycloak
  - otel
  - outline
  - podinfo
  - rook-ceph
  - vaultwarden
  - z-univ
