apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../_base/postgres-18
  - ../../../_base/redis-8
  - nats.yaml

nameSuffix: -my-catatan-kuliah

patches:
  - path: postgres-patch.yaml
  - path: redis-patch.yaml
