apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: caddy-secrets
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: Caddyfile
      remoteRef:
        key: "f3d3e3dc-3e5d-4007-926a-b3bb0120b459"
