apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - extsecret.yaml
  - app-storage.yaml

nameSuffix: -int

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: caddy
      spec:
        serviceName: caddy-int
        template:
          spec:
            nodeSelector:
                type: controller
            volumes:
              - name: caddyfile
                secret:
                  secretName: caddy-secrets-int

        volumeClaimTemplates:
          - metadata:
              name: caddyconfig
            spec:
              storageClassName: manual-caddy-config-int
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 1Gi
          - metadata:
              name: caddydata
            spec:
              storageClassName: manual-caddy-data-int
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 1Gi
