apiVersion: v1
kind: Namespace
metadata:
  name: z-univ
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: z-univ-from-cloudflared
  namespace: z-univ
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cloudflared
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: intra-namespace-z-univ
  namespace: &app z-univ
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: *app
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: z-univ-from-caddy-int
  namespace: z-univ
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: caddy-int
