apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../adguard/core
  - ../dozzle/core
  - ../forgejo/core
  - ../gatus/core
  - ../keycloak/core
  - ../otel/core
  - ../outline/core
  - ../podinfo/core
  - ../rook-ceph/core
  - ../vaultwarden/core
  - ../z-univ/core
